### ISSUE TITLE
JWT Payload 검증 및 캐싱

### ISSUE THREAD

**Issue by beeniyxz** [f-lab-edu/chatAndPay-API#32]
* 탈퇴 등 크리티컬한 로직 처리 시 payload 검증부 필요하다고 판단 -> 추가 예정
* 해당 데이터 검증 부하 관련: 캐싱 처리 

-----

* 경은님 감사합니다 😄

**Comment by f-lab-elkein** [comment]
서버가 보유한 secret key 로 발급된 토큰인지 검사하는 것도 같이 해주시면 좋을 거 같아요.

**Comment by beeniyxz** [comment]
PR 작성을 완료해 이슈를 닫습니다.
